### ISSUE TITLE
Carousel not working with angularjs 1.2.7 + bootstrap 3.0.3

### ISSUE THREAD

**Issue by dinhvan5481** [angular-ui/bootstrap#1565]
I tried to use carousel control, but it's only work on first slide, and then pause forever. The control buttons (prev, and next) didn't work either.

**Comment by MathewSchlabaugh** [comment]
Since this issue was closed when I got here.

If you find this article and are having the same issue.

**Symptom**: The slides stop moving after the first one and buttons don't work.
**Issue**:      ngAnimate and this carousel don't play nicely.
**Resolution**:

Since it really isn't an option for some not to use ngAnimate elsewhere.

This directive disables animations on any element you place it on.

```javascript
angular.module('app').directive('disableAnimations', ['$animate', function ($animate) {
    return {
        restrict: 'A',
        link: function (scope, element) {
            $animate.enabled(false, element);
        }
    };
}]);
```

In this case place it on the carousel.

Example:

&lt;div disable-animations="" carousel=""&gt;&lt;/div&gt;

Viola! :-)

**Comment by Stratus3D** [comment]
I am still experiencing this issue as well. Thankfully @Pleasurazy's workaround fixed the issue for me.

**Comment by Natas0007** [comment]
Yeah i used the directive workaround.  Kinda lame but gets the job done.

**Comment by Stratus3D** [comment]
I actually moved mine to the config block:

app.config(
        ['$animateProvider',
        function ($animateProvider) {
            $animateProvider.classNameFilter(/carousel/);
        }]);

This means ngAnimate is disabled for all elements in the application with the `carousel` class.

**Comment by sonicparke** [comment]
@Stratus3D Thanks! That worked for me.

**Comment by dinesh36** [comment]
@Stratus3D Thanks!  Thanks! Thanks!  Thanks! Thanks! Thanks! That worked for me too.

**Comment by texasinstrument** [comment]
Disabling ngAnimate works for me, but I need animation for elements inside my carousel. Is there a proper fix for this so carousel works with ngAnimate?

**Comment by chrisirhc** [comment]
This is fixed on master.

**Comment by texasinstrument** [comment]
@chrisirhc  I tried using the latest angular ui (0.12.1) bootstrap and also angularJS1.3.14 but it still has the same problem when ngAnimate is included as dependency. Here's plunkr that demonstrate it http://plnkr.co/edit/G9TegO1cgJ2SenBV4I0Z?p=preview

**Comment by rvanbaalen** [comment]
@texasinstrument Like @chrisirhc said, it's fixed in the **master** branch, not in `v0.12.1`. Can you try again by using the master branch?

**Comment by rvanbaalen** [comment]
@texasinstrument Like @chrisirhc said, it's fixed in the **master** branch, not in `v0.12.1`. Can you try again by using the master branch?

**Comment by karianna** [comment]
Closing - can be reopened if OP finds its not fixed on master.

**Comment by deisbel** [comment]
@Stratus3D Thanks! 
I downloaded the module two days ago and the issue is still present. I had to apply the parch!

**Comment by mikethejet** [comment]
The same issue on Bootstrap v3.3.1 and Angular 1.3.10

**Comment by chrisirhc** [comment]
This is on master, it hasn't been released. I think you're referring to downloading the released module on the angular-ui/bootstrap website. The master build can only be obtained by cloning the code and building.

**Comment by stephengardner** [comment]
For those waiting on the release, the above workaround will disable animations on every element except the "carousel" which is, in most cases, undesired.

In order to maintain animations and fix this issue yourself before pulling the new release, add this directive to your `<slide>`s, substituting "myApp" for your app name:

`myApp.directive("disableAnimate", function ($animate) {
	return function (scope, element) {
		$animate.enabled(false, element);
	};
});`

Worked for me

**Comment by ShauneDonohue** [comment]
In my case I was using require.js to load ui-bootstrap, angular-animate was listed as a dependency.  Then in my controller I also had angular-animate as a required module. I am assuming this was causing it to be loaded twice,  removing angular-animate from my controller fixed the problem and angular-animate was still being loaded.
