### ISSUE TITLE
Timestamp treated as invalid model value in datepicker

### ISSUE THREAD

**Issue by oliversalzburg** [angular-ui/bootstrap#2345]
The datepicker directive says [ng-model can be "a number of milliseconds since 01.01.1970"](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L73). However [`parseData` will not treat such an input as valid](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L504).

**Comment by sodatea** [comment]
+1

**Comment by karianna** [comment]
Hi @oliversalzburg - is this with both Angular 1.2.x and 1.3.x?

**Comment by oliversalzburg** [comment]
@karianna I haven't tested this since I reported it. We just moved to a different approach. 1.3 wasn't released when I reported it, but I don't see why the behavior would have changed.

**Comment by khashayar** [comment]
I've added the following line on top of `parseDate()`:

```js
if (angular.isNumber(viewValue)) {
  viewValue = new Date(viewValue);
}
```

Then it goes through the if/else chain and falls into
```js
} else if (angular.isDate(viewValue) && !isNaN(viewValue)) {
```
which handles it correctly.

Updated [Plunker](http://plnkr.co/edit/nTQpcuOTtzAtjIwY09E3?p=preview)

As an alternative we can have this check on if/else chain itself but I didn't want to repeat that part of the chain again.

@karianna Please let me know if you're ok with this, so I'll do a pull request for it.

**Comment by karianna** [comment]
Yes please (and updated/new test as well please).

**Comment by danieljsinclair** [comment]
I also ran into this today and patched mine similarly. I'd also like to be able to write the value back as a timestamp rather than a date object. I'd like to see a timestamp mode that treats the model as a number bidirectionally.

**Comment by khashayar** [comment]
@danieljsinclair Create a directive with the same name as  `datepickerPopup` in your source code:
```javascript
module.directive('datepickerPopup', function () {
  function link(scope, element, attrs, ngModel) {
    // View -> Model
    ngModel.$parsers.push(function (value) {
      return Date.parse(value);
    });
  }

  return {
    restrict: 'A',
    require: 'ngModel',
    link: link
  };
})
```

**Comment by rvanbaalen** [comment]
That is a very solid solution / workaround. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by danieljsinclair** [comment]
Interesting. I didn't think of creating a directive with a matching name. I wrote a similar buddy-directive earlier, but this relies on the datepicker dateParser accepting a timestamp;

        /**
         * Treat dates as a numeric Timestamp - for use with angular-ui/bootstrap/datepicker
         * Processes output from the datepicker and converts to a number
         */
        app.directive('dateAsTimestamp', [function() {

        return {
            require: 'ngModel',
            link: function (scope: ng.IScope, elm: ng.IAugmentedJQuery, attrs: ng.IAttributes, ngModel: ng.INgModelController) {                // Process the output from the datepicker
                ngModel.$parsers.push(function (viewValue: string|number|Date) {

                    if (angular.isDate(viewValue) && !isNaN(<number>viewValue)) {
                        return viewValue.valueOf();
                    }

                    // otherwise - do nothing
                    return viewValue;
                });
            },
        };

    }]);

**Comment by wesleycho** [comment]
This should now be fixed in master.

**Comment by oliversalzburg** [comment]
Cool! Thanks for taking care of this :+1:

**Comment by f1ght4fun** [comment]
Can anyone help as it is still not working for me. I'm on the last 0.14.3 release

"1990-08-01T00:00:00" datetime field is not handled correctly in validator func and returns undefined so on validation form fails

angular.IsNumber and angular.IsDate obv return false when trying to parse this timestamp.

Any ideas?

**Comment by icfantv** [comment]
@f1ght4fun, without any further information it's nearly impossible to provide any assistance.  My first thought is that you're trying to use a string instead of a `Date` object for your `ng-model` on your datepicker.

That said, questions like this are best served by posting them to StackOverflow as documented  [here](https://github.com/angular-ui/bootstrap#need-help).  Posting to already closed issues is a good way for stuff to get missed.
