### ISSUE TITLE
Animation conflict during Modal dismiss/close

### ISSUE THREAD

**Issue by BenBlazely** [angular-ui/bootstrap#2424]
I recently added an "autofocus" directive to a form I have inside a modal and noticed that the modal, when dismissed, would disappear almost immediately without the normal animation running.

I've managed to track the issue down to the removeAfterAnimate function and applied a quick fix to correct the problem I was seeing.

I believe the removeAfterAnimate function was firing on the wrong transitionEndEvent. Specifially, the animation that fires when a bootstrap themed input field loses focus. This caused the function to fire off afterAnimating() prematurely.

I've added a one-line fix to check that the event target node is the same as the backdropDomEl, rather than just firing on any animation that comes along.

```javascript
domEl.bind(transitionEndEventName, function (e) {
    if (e.target === domEl[0]) {
        $timeout.cancel(timeout);
        afterAnimating();
        scope.$apply();
    }
});
```

I've only just started using ui-bootstrap's modals however, so I'm not sure if this change breaks anything that's not immediately obvious to me. What do you think?

B.

**Comment by schackito** [comment]
I have the same issue. Animation is also breaking when using the collapse-directive, not only in modals.

**Comment by chrisirhc** [comment]
I've just merged animation fixes for the modal on master so this issue may not be valid anymore.

**Comment by BenBlazely** [comment]
FYI, with the changes in master the issue I reported is no longer occurring. Nicely done! :-)

**Comment by BenBlazely** [comment]
Sorry, I've found cases where the modal still doesn't close smoothly when another animation on a child  element is running. I'll have a look at the new code in master and see if I can work out a fix for it.

**Comment by chrisirhc** [comment]
Do create a Plunker that demonstrates it, if possible.

**Comment by BenBlazely** [comment]
Will do if I can't track it down today. 

I slowed down the .modal.fade and .fade transitions by a few seconds in bootstrap.css to try and make it easier to see... and it stopped occurring. :(

(not discounting that it could all be in my head)

**Comment by BenBlazely** [comment]
Now I can't reproduce it with the tighter timings back in place either. I wonder if I might have had the old code cached somewhere? Sorry, I'll keep an eye on it.

**Comment by karianna** [comment]
Closing for now in that case
