### ISSUE TITLE
Datepicker shows one day behind when using yyyy-MM-dd format

### ISSUE THREAD

**Issue by bohmanart** [angular-ui/bootstrap#2628]
![screen shot 2014-08-25 at 9 41 29 am](https://cloud.githubusercontent.com/assets/279400/4032403/dc4f6e02-2c6f-11e4-965a-02bd247a94f5.png)

**Comment by dkostenko** [comment]
как же заебал ваш дейтпикер

**Comment by arvind-das** [comment]
But then why this works correctly.
<code>var actualStartDateToPost = $scope.schedule.startDate;</code>

"schedule.startDate" is the model for datepicker.

<code>console.log(actualStartDateToPost.setDate(actualStartDateToPost.getDate()));</code>

prints the time we need.

**Comment by wesleycho** [comment]
This should now be addressed in 0.14.3.

There are still some timezone issues, i.e. the weakness in not being able to configure it, but one can set the timezone used by the datepicker via setting an initial model date value with the appropriate timezone.

**Comment by shrimpwagon** [comment]
This is still not fixed. 

    format: {
        toDisplay: function(date, format, language)
        {
            console.log(date);
        },
	toValue: function(date, format, language)
        {
            return date;
        }
    }

This outputs:

`Tue Sep 06 2016 20:00:00 GMT-0400`

Today is the 7th!

**Comment by charlie-wasp** [comment]
I guess, I am experiencing the same issue right now, version 1.3.3

**Comment by DavidRogersDev** [comment]
I'm experiencing this same issue, and I'm not even concerned with the time of day. I just want to be able to choose a day. Picker keeps picking the day before. Not a good outcome for me.

**Comment by elijahlofgren** [comment]
I ran into this yesterday and found the solution is to set the timezone option to utc and the date is no longer off by one. The syntax for doing that is here: https://github.com/angular-ui/bootstrap/issues/4837#issuecomment-203284205

**Comment by DavidRogersDev** [comment]
Thanks Elijah. But that did not resolve the issue for me. I really wish they would fix this bug, rather than just close the many Issues that people raise which reference it.

**Comment by gbrits** [comment]
If you'd like to _hardcode_ a timezone, you could do what I did. As @charger513 mentioned, you can set the minutes along with the timezone offset -- but instead of determining your current timezone automatically, you could substitute the timezone offset with the amount of minutes - in my case, my local timezone was returning `-660 (UTC-11)`. But I needed it to be `480 (UTC+08)`.

```
var d = new Date('yourDate');
d.setMinutes( d.getMinutes() + 480 );
```

I was then finally getting the output I wanted - as my PHP backend counterpart was aligned to the UTC+08 timezone.

Find your timezone minutes offset here: https://forbrains.co.uk/international_tools/earth_timezones

**Comment by gauravgtex007** [comment]
I have found a way. convert that date to string first.
here is the code. 

 

     var SelectDate = $scope.GetFormattedDate(Date.parse($("#Date").datepicker("getDate")));            
         $scope.GetFormattedDate = function (CalDate) {
                var re = /-?\d+/;
                var WDate = CalDate.toString();
                var m = re.exec(WDate);
                var lastDate = new Date(parseInt(m[0]));
                var mm = lastDate.getMonth() + 1;
                var dd = lastDate.getDate();
                var yyyy = lastDate.getFullYear();
                var formattedDate = mm + '/' + dd + '/' + yyyy;
        
                return formattedDate;
            }

Now Pass SelectDate to your controller.
bingo problem has been resolved :)

**Comment by mvelebit** [comment]
Can't believe this is still a bug..

**Comment by maverick1812** [comment]
I solved this issue by giving the Date field in Backend as Edm.DateTimeOffset (this will be a Timestamp field in ABAP) & converting the timestamp field to Date & Time by using function module - IB_CONVERT_FROM_TIMESTAMP.

**Comment by vishnucr** [comment]
if you are using moment, you can user the 'utc date'
`moment.utc('23-12-2011')`

**Comment by NDMCreative** [comment]
This works for me

var DatePickerDate ='Thu Aug 09 2018 00:00:00 GMT+0100 (British Summer Time)';

var myDate = new Date(DatePickerDate).toISOString();

so myDate is now 2018-08-08T23:00:00.000Z

**Comment by ricksonmenezes** [comment]
If you are using Java-Hibernate, use the Date as type String in your Model(POJO) when reaching the controller to collect ModelAttribute. This issue occurs If you use it as type DateTime in your Java.

**Comment by junaid003** [comment]
+1

**Comment by D252874** [comment]
when will this be fixed I still got the same problem using the latest version of angular and material. but I am not using yyyy-mm-dd I am just using standard material date picker.
