### ISSUE TITLE
typeahead-on-select is not being fired when selecting a item with the mouse and batarang is enabled

### ISSUE THREAD

**Issue by kdekooter** [angular-ui/bootstrap#3101]
`typeahead-on-select` is not being fired when selecting an item with the mouse. Tested with angular-bootstrap 0.12.0 and angular 1.3.6

**Comment by thardy** [comment]
Just to be clear, this "fix" is not ideal.  It's just a hack.  If the user clicks elsewhere on the screen (usually with the intent to take no action), whatever item was highlighted will be selected.

What we need is for a real fix to be put in place.  A fix that allows a mouse click to select an item in an angular-ui typeahead.  We need typeahead to work the way it was intended.

**Comment by thardy** [comment]
To reiterate the versions, mouse clicks aren't selecting an item using ui-bootstrap 0.12.0 and Angular 1.2.27 and 1.2.28.  This isn't just an issue with angular 1.3.x.

**Comment by thardy** [comment]
In trying to distill this down into a simple demo to display the problem, my problem with the above versions went away.  We are using a nasty combo of jquery mobile plus angular, so I'm not at all surprised.  That's the value in trying to distill the problem.  Angular 1.2.27 and ui-bootstrap 0.12.0 do not appear to have this problem.

**Comment by kdekooter** [comment]
Working for me now with angular 1.3.8, angular-bootstrap 0.12.0 and jquery 2.1.3

**Comment by bbobrian** [comment]
Updated my versions last week and just noticed the same combo of versions is also not working for me (angular 1.3.8, ui 0.12, jquery 2.1.3). I'm using the all-in-one ui-bootstrap.tpls.js version.

Selecting by keyboard with enter key does correctly fire typeahead-on-select callback.

Was working previously on angular 1.3.4, ui 0.12, jquery 2.1.1.

Using patch from @thardy to get it working.

**Comment by skfd** [comment]
Excuse me, what version combination does not have this problem?

**Comment by danielbsig** [comment]
I'm experiencing this as well. angular v1.2.28, angular-bootstrap v.0.12.0

**Comment by uqcgreen** [comment]
Same here, angular 1.3.0, angular-bootstrap 0.10

**Comment by luiselizondo** [comment]
Same problem, the mouse click doesn't do anything, using Angular 1.3.2 and Angular-Bootstrap 0.11.2

**Comment by rbj325** [comment]
So this isn't perfect but at least it maintains what I believe is supposed to be the default behavior of the typeahead.  Beyond what @thardy proposed I only wanted the item to be selected if the user clicks an item in the actual typeahead list:

// Proposed patch: select the clicked item(only if clicking on the typeahead dropdown)
              if(evt.target.parentElement.id.indexOf("typeahead") != -1) {
                  scope.$apply(function () {
                      if (scope.activeIdx != -1) {
                          scope.select(scope.activeIdx);
                      }
                  });
              }

There is probably a better way to detect this but this is just my quick and dirty proposal.

**Comment by danielbsig** [comment]
@rbj325 : is this something for people to put into their own code, or is this a change in the library?

**Comment by rbj325** [comment]
@danielbsig This is a change to the library, in the typeahead module.  The above code goes into the dismissClickHandler function.

**Comment by Schaemelhout** [comment]
I'm experiencing issue with angular 1.2.23 and angular-bootstrap v.0.12

**Comment by wesleycho** [comment]
I am not able to reproduce this [here](http://plnkr.co/edit/qICS4RPjJ52g8DzibuYR?p=preview) with the current master - in fact, it appears to be working.

There is a possibility that this was fixed.  Closing this as it seems invalid currently.

If someone is able to reproduce this based on current master, then post it here and I will reopen the ticket & investigate further.

**Comment by danielbsig** [comment]
I agree that this works in the plunker example. I also copied the files from the example to a Public folder in my Dropbox, and viewed the public link to the index.html file in a browser, and it works there.

However, if I copy the files to another directory, and start a python webserver (python -m SimpleHTTPServer 8080, assuming Python 2.7 is installed on the machine), then the bug emerges. I also experience the bug in my project, which uses grunt-contrib-connect as a web server.

Any idea what could possibly cause this?

**Comment by danielbsig** [comment]
Just to clarify: in order to reproduce, it should be enough to copy the files from the plunkr example (index.html and example.js) to a local folder, run the "python -m SimpleHTTPServer 8080" from that folder and then run the example by entering localhost:8080 in the browser.

**Comment by danielbsig** [comment]
To clarify even further: the problem disappears if the IP address (i.e. 127.0.0.1) is used instead of "localhost".

**Comment by chrisirhc** [comment]
That's odd, it sounds like a caching problem. Is the problem still there if you clear your cache, load the page with Shift+Refresh or use another browser? Also, which browser are you using?

**Comment by chrisirhc** [comment]
I still can't seem to reproduce this, can you create a Plunker where this issue is occurring?

**Comment by shurique** [comment]
@danielbsig Any chance that you are using Chrome + AngularJS Batarang (or something like that)? I faced with the same problem. And reproduced fully with you instructions. Removing Batarang solve this bug. I think thats why ... localhost -> 127.0.0.1 and thats why it's not reproduced in Plunker.

**Comment by skfd** [comment]
Wow. @shurique is right. I tried it in anonymous window and it works fine.

**Comment by Schaemelhout** [comment]
@shurique That's right, AngularJS Batarang seems to be the troublemaker! Works fine without, thanks

**Comment by danielbsig** [comment]
Confirmed. Works correctly in other browsers, and in incognito mode in Chrome.

**Comment by Microserf** [comment]
Just want to add my +1 for seeing the problem with both (localhost + Batarang). I can confirm that I *don't* see the issue on (https://angular-ui.github.io/bootstrap/ + Batarang).

I haven't tested yet on localhost without Batarang, but I'll try tonight and report back.

**Comment by Microserf** [comment]
I can now confirm that the bug becomes manifest when Batarang is enabled, and disappears when Batarang is disabled. Seems like a smoking gun to me...

**Comment by karianna** [comment]
Hopefully one of the more experienced maintainers can chime in with a fix/workaround...

**Comment by chrisirhc** [comment]
Most probably related to https://github.com/angular/angularjs-batarang/issues/205 . Please subscribe for updates on angularjs-batarang and only comment here if there's anything new to report. Otherwise, there's nothing we can (or should) do on this library.

**Comment by adamhaeger** [comment]
@chrisirhc I'm experiencing this problem both with and without batarang in chrome, and also on firefox 37.02. Running angular 1.3.15 and ui-bootstrap-tpls 0.12.1.

**Comment by yaelz** [comment]
@chrisirhc same here, with angular 1.3.15 and angular-bootstrap 0.13.0. Chrome and Firefox with and without batarang and in incognito.

**Comment by wesleycho** [comment]
@adamhaeger can you try reproducing this with the latest versions (angular 1.4 & UI Bootstrap 0.13.2)?

**Comment by wesleycho** [comment]
Closing, as this appears to have been fixed in Batarang.

**Comment by hdngr** [comment]
+1

**Comment by Rykie** [comment]
Hate to bring it up again, but I am using angularjs 1.4.5 and UI Bootstrap 0.13.4 and I still have this issue.

**Comment by brick80** [comment]
hope this helps.
i had a similar problem with ui-grid editable feature.
i "fixed" by using the following typeahead setting on my input
typeahead-select-on-blur="true"

**Comment by dedan** [comment]
I have the same issue on 

```
    "angular": "^1.4.7",
    "angular-ui-bootstrap": "^0.14.3",
```

**Comment by groovepile** [comment]
I fixed this issue by adding the following attribute to my <input> tags:
autocomplete="off"

**Comment by lagivan** [comment]
Should be reopened, apparently the issue is not solved.

I've faced the same issue with angular 1.5.7, angular-ui-bootstrap 1.3.3. I've used a workaround by setting ```typeahead-select-on-blur="true"```.

**Comment by LachezarLechev** [comment]
Thank you @lagivan ! I've being looking for this fix!
