### ISSUE TITLE
Modal should also add "modal-open" class to html, not only body

### ISSUE THREAD

**Issue by Hirbod** [angular-ui/bootstrap#3845]
Hi,

everything said in the title. In some cases, it isn't just enough to add overflow: hidden to the body. I'm working a lot with height: 100% and therefore, I need to set the height both on html and body to inherit the height to the children nodes.

Have a look at the screenshot.

![bildschirmfoto 2015-06-22 um 21 42 34](https://cloud.githubusercontent.com/assets/504909/8291146/e93d0f48-1927-11e5-857c-26558363398b.png)

Currently I've made a workaround with modalInstance.opened and .result to add/remove the class from 
``` $('html') ```

**Comment by Janjuks** [comment]
+1. I have done exactly the same thing because of the same problem.

**Comment by icfantv** [comment]
Hey guys, can you please create a bare bones plunker that shows the issue?  Thanks.

**Comment by wesleycho** [comment]
This doesn't smell right to me - the example in Bootstrap's own site shows it only being present on the body element.

As @icfantv mentioned, this needs a Plunker.

**Comment by Janjuks** [comment]
Found out that this happens when `overflow-x:hidden;` is set for `html`. Plunker here: http://plnkr.co/edit/mUHFVduK7CRfiDdrTgax?p=preview

**Comment by wesleycho** [comment]
This seems solved with CSS, as can be seen [here](http://plnkr.co/edit/KokccUWt8rYKZuQx0OGG?p=preview).

One should never set `html` and `body` to `height: 100%` simultaneously.

Closing, as this appears to be a user CSS issue.

**Comment by Janjuks** [comment]
I am looking at your plunker and don't see any difference in result. The bug still appears. Also, you can see in my plunker that I haven't set `height: 100%` to any of those elements. The problem is with `overflox-x: hidden;` for `html`.
