### ISSUE TITLE
keyboard-nav directive for dropdown menu throws error when using up arrow first

### ISSUE THREAD

**Issue by jfarago** [angular-ui/bootstrap#4327]
When you click on a drop down menu and hit the up arrow the following error is thrown. Uncaught TypeError: Cannot read property 'focus' of undefined

If you hit down first and then up it is not an issue

**Comment by icfantv** [comment]
This is fixed in master.

**Comment by jfarago** [comment]
Thank you

**Comment by jfarago** [comment]
Installed the master, which resolved to angular-bootstrap#0b83ef6828, and the problem persists.

**Comment by icfantv** [comment]
Crud.  Yea, this is a bug.  You can reproduce via [this plunker](http://plnkr.co/edit/YZ2woGMgABThe7CgGYBC) which was used to fix #4091.

**Comment by icfantv** [comment]
Hang on.  That plunker is not using the latest code.  I fixed #4091 and there were at least three issues.  I need to test again w/ the latest code.

**Comment by icfantv** [comment]
Yea, this is a bug.  [Here's](http://plnkr.co/edit/dKdCkETiZenQE53OREwe) an updated plunker.  The problem is that `dropdownCtrl.selectedOption` is coming back as `null` so the ternary operator is setting `dropdownCtrl.selectedOption` to `-1` because in JavaScript `null - 1 === -1` and you can't have a `-1` index into an array.

**Comment by jfarago** [comment]
Thank you for your quick response time fixing this bug

**Comment by icfantv** [comment]
You're welcome.  Just a note that ARIA does not specifically state that for menus, the up arrow should wrap and select the bottom (which is weird because it does for other widges - I saw at least accordion and radio groups).

That said, as I play with a menu on my Mac, it does wrap - which I think is the right use case.
