### ISSUE TITLE
tooltip can be null in timeout 0.14.3

### ISSUE THREAD

**Issue by frfancha** [angular-ui/bootstrap#5029]
In the function positionTooltip, if the tooltip is null one returns immediately, otherwise a $timeout is called.
In the $timeout, tooltip is used without testing again if it is null or not.
Since we have upgraded to 0.14.3, several "quick" users have received the message "tooltip is null" from the line tooltip.css({ top: 0, left: 0 }); in the $timeout.
It is difficult to reproduce but happens several times a day.
Just testing again if tooltip is null or not at the beginning of the timeout code is enough to fix the problem.

@icfantv I've searched in the recent tooltip issues and didn't find any mention of this one ;-)

**Comment by wesleycho** [comment]
I believe this is actually fixed in `master` - we just need to do our 1.0 release, which should be within this month.

**Comment by frfancha** [comment]
Ok great (I had checked with the code of master as it was 4 days ago, and then it wasn't fixed yet)

**Comment by wesleycho** [comment]
Can you post a simple reproduction in Plunker with current `master` so we can take a look at it then?

@RobJacobs do you have any clue whether this situation is still possible with the current tooltip?

**Comment by frfancha** [comment]
Unfortunately, it isn't an easily reproducible problem. It only happens from times to times.
The only thing we know is that when it happens the user was putting the mouse on a button (with tooltip) and almost immediately clicked the button. When you try to reproduce it, trying 10 times, it doesn't happen... then just as you think it won't happen again... it comes back!
For us it isn't very annoying as the by-pass is clear, just add the condition "if (tooltip) ..." in the $timeout code, my goal in opening this issue is just to let you know so you can enhance the code for everybody.

**Comment by wesleycho** [comment]
I appreciate reporting it, I just want us to get to the root of this since it isn't exactly a new problem - we've wrestled with it some in the past couple of months.

It is likely an issue with garbage collection of the tooltip before the $timeout resolves, but as far as I can see in the tooltip code, there is a check for whether the tooltip exists before the $timeout is scheduled, which confuses me.

**Comment by frfancha** [comment]
Reading the code, the only explanation I see is that the function removeTooltip, setting tooltip to null, is called between the time $timeout is scheduled and the time it is run.
If you want I can add simple console.log before $timeout, in removeTooltip and in the $timeout to try to confirm this cause.

**Comment by wesleycho** [comment]
More information would be welcome, and assist us in pinpointing this!

**Comment by RobJacobs** [comment]
This was reported under #4757 and fixed under #4765.

**Comment by frfancha** [comment]
Ok, great. Sorry I didn't find it by myself. I had only searched issues from Nov, 1 and later.
