### ISSUE TITLE
Bug: min and max attribute check old value at time of change value of timepicker

### ISSUE THREAD

**Issue by ketansomani** [angular-ui/bootstrap#5147]
Hello,

i am using "ui-bootstrap-tpls-0.14.3.js" for datepicker and timepicker.
This bug occur when i  set value of timepicker on select date of datepicker.

Following is my  plunker link.

http://plnkr.co/edit/L4A4HLQbJFxeN2e7r3XF?p=preview

What i do is when i change date, on that date i set timepicker value with min and  max attribute.
but timepicker value check time with old min and max attribute and it give validation error as red box.

For reproduce case.

Step 1: Run code
Step 2: Select any future date from datepicker.  //It show red box on timepicker value
Step 3: Just do hour increment in timpicker and then do hour decrement. //This automatic remove validation error for same value.

I also debug your liabrary, in that when we change value of timepicker it check value with old min and max attribute value then it update max and min value.

Please let me know what i do in this  case.

Thank you.

**Comment by Nicklas-Coker** [comment]
Im having the same problem can we please have a fix

**Comment by wesleycho** [comment]
According to the documentation, the min and max values are not dynamic (i.e. not watched for), but static.

This would be a feature request to allow dynamic updates of the min and max properties.

**Comment by ketansomani** [comment]
Hey,

May be i wrong in following statement,

If i look at  "ui-bootstrap-tpls-0.14.3.js" library. min and max value watch by  library, and also  it update dynamically but it update after the timepicker value check by old min and max value.


Following code snippet which is  available in "ui-bootstrap-tpls-0.14.3.js" to update min and max  value.

var min;
  $scope.$parent.$watch($parse($attrs.min), function(value) {
    var dt = new Date(value);
    min = isNaN(dt) ? undefined : dt;
  });

  var max;
  $scope.$parent.$watch($parse($attrs.max), function(value) {
    var dt = new Date(value);
    max = isNaN(dt) ? undefined : dt;
  });


So according to code min and max value update dynamically.


Please have a fix for that.

Thank you

**Comment by Nicklas-Coker** [comment]
It updates the min and max values but the arrows on the ui are not disabled
to reflect the new min and max date that is set when let say u are watching
a model that u want to use its value for this purpose. It only disables
them when the page is loaded for the first time.

**Comment by wesleycho** [comment]
The arrows are currently fixed in `master` - the bug there is on just the template, should be easy to swap the current template in if you want a quick fix to that. That was a separate issue.

**Comment by ketansomani** [comment]
Hey wesleycho,

Still my problem not solved.
Please look again on this problem.

i am using "ui-bootstrap-tpls-0.14.3.js" for datepicker and timepicker.
This bug occur when i set value of timepicker on select date of datepicker.

Following is my plunker link.

http://plnkr.co/edit/L4A4HLQbJFxeN2e7r3XF?p=preview

When i change date, on that date i set timepicker value with min and max attribute.
but timepicker value check time with old min and max attribute and it give validation error as red box.

For reproduce case.

Step 1: Run code
Step 2: Select any future date from datepicker. //It show red box on timepicker value
Step 3: Just do hour increment in timpicker and then do hour decrement. //This automatic remove validation error for same value.

I also debug your liabrary, in that when we change value of timepicker it check value with old min and max attribute value then it update max and min value.

Please let me know what i do in this case.

Thank you.

**Comment by wesleycho** [comment]
@ketansomani I was responding to @Nicklas-Coker - there is no need to respond to every response.

This still needs looking into, hence why the issue is still open.

**Comment by Nicklas-Coker** [comment]
Hi thanx for the reply. I havent gotten around to get the new template. But
thanks alot

**Comment by wesleycho** [comment]
So there are two separate issues here - a validation issue (due to ngModelCtrl.$validators not being used) for the first issue of when one updates the date model programmatically, and an issue with validators not being run when min/max values change.

This will potentially require a lot of refactoring to fix.

**Comment by icfantv** [comment]
Closing in favor of #5957 as this will result in a complete rewrite of the widget, addressing all the outstanding issues.
