### ISSUE TITLE
multiple uib-dropdown components keyboard-nav issue

### ISSUE THREAD

**Issue by ashraffsmd** [angular-ui/bootstrap#6335]
### Bug description: If there are multiple uib-dropdown components in a single page with keyboard-nav enabled, clicking on second dropdown while first dropdown still open breaks keyboard navigation for the second dropdown.

Steps to reproduce:

1. Open the link to plunker provided.
2. Click on first dropdown and check keyboard navigation which is working fine.
3. Without closing the first dropdown, click on second dropdown and check keyboard navigation for this.

Expected: When down arrow is pressed, 'Action' option should be selected.

Actual: 'Another action' option is selected.

After that, the keyboard navigation is not working as expected for all the dropdowns.

Note that this issue is similar to [#6314](https://github.com/angular-ui/bootstrap/issues/6314). While it talks only about a keyboard-nav enabled dropdown and a non keyboard-nav enabled dropdown, the current issue talks about keyboard navigation issue in multiple dropdown components in a single page.

PS: Tried incorporating [#6314](https://github.com/angular-ui/bootstrap/issues/6314)'s fix to check if it fixes the current issue. But when that fix is added, the second dropdown keyboard navigation is not triggered at all.

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/kGDpkqYPdY5B4RPxAxB8?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.3.0

Bootstrap: 3.3.7

**Comment by wesleycho** [comment]
Closing as fixed by 44ab0a81061769dd038ac218a12131cde5bf9e67 - will be in the next release.

**Comment by ashraffsmd** [comment]
The fix by 44ab0a8 doesn't solve the issue. As mentioned in the PS above, the second dropdown keyboard navigation is not triggered at all after that fix is incorporated.

**Comment by wesleycho** [comment]
I'm not sure this is fixable in a good way - having multiple dropdowns open simultaneously is a terrible idea and should be avoided at all costs. The problem is that we have no good way of knowing what is the intended active dropdown. Even worse, this is prone to memory leaks as it is.

I'm inclined to not support this use case.

**Comment by ashraffsmd** [comment]
@wesleycho The use case is not supporting multiple dropdowns opening simultaneously. We want on clicking on second dropdown while first dropdown still open, closes the first dropdown and opens the second dropdown, while still supporting keyboard navigation for the second dropdown. At any point of time, only one dropdown will be open.
Let me explain my usecase. Consider two dropdowns D1 & D2, both with keyboard navigation enabled.
1. Clicking on D1 opens it up, and keyboard navigation works fine.
2. Click anywhere outside D1, except on D2. D1 closes. Now click on D2. D2 opens and keyboard nav works fine for D2 as well.
3. Now click anywhere outside D2, except on D1. The behaviour is same which is good.
4. Open D1 where keyboard nav works fine, and then click on D2 to open, while still D1 is open. This closes D1, opens up D2. But now, keyboard nav on D2 is broken. The expectation is keyboard nav on D2 now still should work.
The #4 above is the use case I am discussing about.

**Comment by ashraffsmd** [comment]
@wesleycho Any update on this?

**Comment by ashraffsmd** [comment]
@wesleycho Gentle reminder
